<?php

namespace Swap\PlatformBundle\Repository;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeletedDateRepository extends \Doctrine\ORM\EntityRepository
{
}