<?php

namespace Swap\PlatformBundle\Repository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{
	public function recuperationConversation($idUser)
    {
		$qb = $this->createQueryBuilder('m');

		$qb
		->where('m.parentId is null')
		->andWhere($qb->expr()->orX(
	      $qb->expr()->eq('m.author', $idUser),
	      $qb->expr()->eq('m.recipient', $idUser)
	   	))
		;

		return $qb
		->getQuery()
		->getResult();
	}

	public function commentRecovery($idRecipient)
    {
		$qb = $this->createQueryBuilder('m');

		$qb
		->where('m.recipient = :recipient')
		->setParameter('recipient', $idRecipient)
		->andWhere($qb->expr()->orX(
	      $qb->expr()->eq('m.comment', '1')
	   	))
		;

		return $qb
		->getQuery()
		->getResult();
	}
}

