<?php

namespace Swap\PlatformBundle\Repository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
	public function reservationNb($idUser)
    {
		$qb = $this->createQueryBuilder('m');

		$qb
		->andWhere('m.status is :notification')
		->setParameter('notification', '2')  
		;

		return $qb
		->getQuery()
		->getResult();
	}
}
