swap_platform_reservation:
    resource: "@SwapPlatformBundle/Resources/config/routing/reservation.yml"
    prefix:   /reservation

swap_platform_service:
    resource: "@SwapPlatformBundle/Resources/config/routing/service.yml"
    prefix:   /service

swap_platform_homepage:
    path:     /
    defaults: { _controller: SwapPlatformBundle:Index:display }

swap_platform_admin:
    path:     /admi
    defaults: { _controller: SwapPlatformBundle:Index:admin }

swap_platform_moncompte:
    path:     /compte
    defaults: { _controller: SwapPlatformBundle:Profil:account }

swap_platform_profil:
    path:     /profil
    defaults: { _controller: SwapPlatformBundle:Profil:profil }

swap_platform_inscription:
    path:     /inscription
    defaults: { _controller: SwapPlatformBundle:Profil:inscription }

swap_platform_modal:
    path:     /modal
    defaults: { _controller: SwapPlatformBundle:ModalInscription:modal }

swap_ajouter_service:
    path:     /ajouter-swap
    defaults: { _controller: SwapPlatformBundle:Swap:addSwap }

swap_delete:
    path:     /supprimer-swap/{serviceId}/{delete}
    defaults: 
        _controller: SwapPlatformBundle:Swap:deleteSwap
        delete: 'no'

swap_ajouter_service_details:
    path:     /ajouter-swap-details/{id}
    defaults: { _controller: SwapPlatformBundle:Swap:detailsSwap }

swap_search:
    path:     /rechercher-swap
    defaults: { _controller: SwapPlatformBundle:Swap:search }

ajax_search:
    path:     /ajax
    defaults: { _controller: SwapPlatformBundle:Swap:ajax }

swap_calendar:
    path:     /swap-calendrier/{serviceId}
    defaults: { _controller: SwapPlatformBundle:Swap:manageCalendar }

swap_calendar_reactivate_date:
    path:     /reactivate-date
    defaults: { _controller: SwapPlatformBundle:Swap:reactivateDate }

swap_manage_swap:
    path:     /manage-swaps
    defaults: { _controller: SwapPlatformBundle:Swap:manageMySwaps }

swap_focus:
    path:     /swap/{id}
    defaults: { _controller: SwapPlatformBundle:Reservation:resa }

swap_message_send:
    path:     /send-message/{id}/{idUser}
    defaults: { _controller: SwapPlatformBundle:Message:sendMessage }

swap_mail_box:
    path:     /mail-box/
    defaults: { _controller: SwapPlatformBundle:Message:mailBox}

swap_message_conversation:
    path:     /message-conversation/{serviceId}/{idMessage}/{recipientId}
    defaults: { _controller: SwapPlatformBundle:Message:conversation}

swap_notification_delete:
    path:     /delete-notification/{id}
    defaults: { _controller: SwapPlatformBundle:Notification:delete}

swap_send_comment:
    path:     /send-comment/{id}
    defaults: { _controller: SwapPlatformBundle:Comment:send}