<?php

namespace Swap\PlatformBundle\Repository;

/**
 * MembreInscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembreInscriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
