user_index:
    path:     /
    defaults: { _controller: "SwapUserBundle:CrudUser:index" }
    methods:  GET

user_show:
    path:     /{id}/show
    defaults: { _controller: "SwapUserBundle:CrudUser:show" }
    methods:  GET

user_new:
    path:     /new
    defaults: { _controller: "SwapUserBundle:CrudUser:new" }
    methods:  [GET, POST]

user_edit:
    path:     /{id}/edit
    defaults: { _controller: "SwapUserBundle:CrudUser:edit" }
    methods:  [GET, POST]

user_delete:
    path:     /{id}/delete
    defaults: { _controller: "SwapUserBundle:CrudUser:delete" }
    methods:  DELETE
